// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  features: dynamic(() => import("./Features")),
  hero1: dynamic(() => import("./Hero1")),
  testimonials: dynamic(() => import("./Testimonials")),
};
